modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="chrisomode"
version="1.1.1"
displayName="chriso mode"
credits="This shit mod was made by me, Zanman248, so were all the textures"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Zanman248"
description='''
So this started as an april fools joke for my freind chris, and then i never stopped developing it, so here you go
'''

[[dependencies.chrisomode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



